import {
  Vote,
  ShieldCheck,
  ShieldAlert,
  Landmark,
  Users,
  Scale,
  FileCheck2,
  Lock,
  LockKeyhole,
  WifiOff,
  Cpu,
  MonitorCheck,
  PrinterCheck,
  ScanEye,
  PackageCheck,
  Truck,
  CalendarCheck,
  CalendarClock,
  ClipboardCheck,
  ClipboardList,
  CheckCircle2,
  CircleX,
  Info,
  History,
  Sparkles,
  MapPin,
  School,
  HandHeart,
  Megaphone,
  BookOpenCheck,
  Code2,
  Briefcase,
  PlayCircle,
  Camera,
  Globe,
  BatteryCharging,
  KeyRound,
  Stamp,
  TicketCheck,
  Database,
  Eye,
  AlertTriangle,
  Flag,
  type LucideProps,
} from "lucide-react";
import type { IconName } from "@/types";

const iconMap: Record<IconName, React.ComponentType<LucideProps>> = {
  vote: Vote,
  "shield-check": ShieldCheck,
  "shield-alert": ShieldAlert,
  landmark: Landmark,
  users: Users,
  scale: Scale,
  "file-check-2": FileCheck2,
  lock: Lock,
  "lock-keyhole": LockKeyhole,
  "wifi-off": WifiOff,
  cpu: Cpu,
  "monitor-check": MonitorCheck,
  "printer-check": PrinterCheck,
  "scan-eye": ScanEye,
  "package-check": PackageCheck,
  truck: Truck,
  "calendar-check": CalendarCheck,
  "calendar-clock": CalendarClock,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  "check-circle-2": CheckCircle2,
  "circle-x": CircleX,
  info: Info,
  history: History,
  sparkles: Sparkles,
  "map-pin": MapPin,
  school: School,
  "hand-heart": HandHeart,
  megaphone: Megaphone,
  "book-open-check": BookOpenCheck,
  github: Code2,
  linkedin: Briefcase,
  youtube: PlayCircle,
  instagram: Camera,
  globe: Globe,
  "battery-charging": BatteryCharging,
  "key-round": KeyRound,
  stamp: Stamp,
  "ticket-check": TicketCheck,
  database: Database,
  eye: Eye,
  "alert-triangle": AlertTriangle,
  flag: Flag,
};

export function getIcon(name: IconName): React.ComponentType<LucideProps> {
  return iconMap[name];
}
